apiVersion: v1
kind: Service
metadata:
  name: springkube-k8s-service

spec:
  selector:
    app: springkube-k8s

  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080

  type: NodePort